global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'services'
    metrics_path: '/_metrics'
    static_configs:
      - targets:
          - 'async-simple:8082'
          - 'async-abort:8082'
          - 'consumer:8082'
          - 'sync-abort:8082'
          - 'sync-abort-multiple:8082'
          - 'sync-multiple:8082'
          - 'sync-simple:8082'
  - job_name: 'kafka'
    static_configs:
      - targets:
          - 'kafka:9092'