global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'async-abort'
    metrics_path: '/_metrics'
    static_configs:
      - targets: ['async-abort:8082']

  - job_name: 'async-simple'
    metrics_path: '/_metrics'
    static_configs:
      - targets: ['async-simple:8082']

  - job_name: 'consumer'
    metrics_path: '/_metrics'
    static_configs:
      - targets: ['consumer:8082']

  - job_name: 'sync-abort'
    metrics_path: '/_metrics'
    static_configs:
      - targets: ['sync-abort:8082']

  - job_name: 'sync-abort-multiple'
    metrics_path: '/_metrics'
    static_configs:
      - targets: ['sync-abort-multiple:8082']

  - job_name: 'sync-multiple'
    metrics_path: '/_metrics'
    static_configs:
      - targets: ['sync-multiple:8082']

  - job_name: 'sync-simple'
    metrics_path: '/_metrics'
    static_configs:
      - targets: ['sync-simple:8082']